name: flutter_finder_usercentric
description: "Flutter usercentric finder provides flutter finder based on usercentric approach and ready to use during test"
version: 0.0.1-beta.1
homepage: https://orange-opensource.github.io/uuv/
repository: https://github.com/Orange-OpenSource/uuv.git

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0

flutter:
