name: 'CI'

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

env:
  NODE_VERSION: 18.14.0
  FLUTTER_VERSION: '3.16.9'

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: 'stable'
      - run: flutter analyse

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: 'stable'
      - run: flutter test

  release:
    if: github.ref == 'refs/heads/main'
    needs: [ analyse, test ]
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Use Node.js ${{env.NODE_VERSION}}
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
      - name: Build new release
        run: npx semantic-release
        shell: bash

  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [ release ]
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
          channel: 'stable'
      - name: Publish on pub.dev
        run: dart publish
        shell: bash
